# permissions for end users to edit servingclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servingcluster-editor-role
rules:
- apiGroups:
  - ray.io
  resources:
  - servingclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ray.io
  resources:
  - servingclusters/status
  verbs:
  - get
