//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayActorOptionSpec) DeepCopyInto(out *RayActorOptionSpec) {
	*out = *in
	if in.RuntimeEnv != nil {
		in, out := &in.RuntimeEnv, &out.RuntimeEnv
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NumCpus != nil {
		in, out := &in.NumCpus, &out.NumCpus
		*out = new(int32)
		**out = **in
	}
	if in.NumGpus != nil {
		in, out := &in.NumGpus, &out.NumGpus
		*out = new(int32)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(int32)
		**out = **in
	}
	if in.ObjectStoreMemory != nil {
		in, out := &in.ObjectStoreMemory, &out.ObjectStoreMemory
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayActorOptionSpec.
func (in *RayActorOptionSpec) DeepCopy() *RayActorOptionSpec {
	if in == nil {
		return nil
	}
	out := new(RayActorOptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServeConfigSpec) DeepCopyInto(out *ServeConfigSpec) {
	*out = *in
	if in.InitArgs != nil {
		in, out := &in.InitArgs, &out.InitArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InitKwargs != nil {
		in, out := &in.InitKwargs, &out.InitKwargs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NumReplicas != nil {
		in, out := &in.NumReplicas, &out.NumReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxConcurrentQueries != nil {
		in, out := &in.MaxConcurrentQueries, &out.MaxConcurrentQueries
		*out = new(int32)
		**out = **in
	}
	if in.UserConfig != nil {
		in, out := &in.UserConfig, &out.UserConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AutoscalingConfig != nil {
		in, out := &in.AutoscalingConfig, &out.AutoscalingConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GracefulShutdownWaitLoopS != nil {
		in, out := &in.GracefulShutdownWaitLoopS, &out.GracefulShutdownWaitLoopS
		*out = new(int32)
		**out = **in
	}
	if in.GracefulShutdownTimeoutS != nil {
		in, out := &in.GracefulShutdownTimeoutS, &out.GracefulShutdownTimeoutS
		*out = new(int32)
		**out = **in
	}
	if in.HealthCheckPeriodS != nil {
		in, out := &in.HealthCheckPeriodS, &out.HealthCheckPeriodS
		*out = new(int32)
		**out = **in
	}
	if in.HealthCheckTimeoutS != nil {
		in, out := &in.HealthCheckTimeoutS, &out.HealthCheckTimeoutS
		*out = new(int32)
		**out = **in
	}
	in.RayActorOptions.DeepCopyInto(&out.RayActorOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServeConfigSpec.
func (in *ServeConfigSpec) DeepCopy() *ServeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ServeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServeStatus) DeepCopyInto(out *ServeStatus) {
	*out = *in
	if in.NumReplicas != nil {
		in, out := &in.NumReplicas, &out.NumReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServeStatus.
func (in *ServeStatus) DeepCopy() *ServeStatus {
	if in == nil {
		return nil
	}
	out := new(ServeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingCluster) DeepCopyInto(out *ServingCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingCluster.
func (in *ServingCluster) DeepCopy() *ServingCluster {
	if in == nil {
		return nil
	}
	out := new(ServingCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServingCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingClusterList) DeepCopyInto(out *ServingClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServingCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingClusterList.
func (in *ServingClusterList) DeepCopy() *ServingClusterList {
	if in == nil {
		return nil
	}
	out := new(ServingClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServingClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingClusterSpec) DeepCopyInto(out *ServingClusterSpec) {
	*out = *in
	if in.HealthCheckProbe != nil {
		in, out := &in.HealthCheckProbe, &out.HealthCheckProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ServeConfigSpecs != nil {
		in, out := &in.ServeConfigSpecs, &out.ServeConfigSpecs
		*out = make([]ServeConfigSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.RayClusterSpec.DeepCopyInto(&out.RayClusterSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingClusterSpec.
func (in *ServingClusterSpec) DeepCopy() *ServingClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ServingClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingClusterStatus) DeepCopyInto(out *ServingClusterStatus) {
	*out = *in
	if in.ServeStatuses != nil {
		in, out := &in.ServeStatuses, &out.ServeStatuses
		*out = make([]ServeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.RayClusterStatus.DeepCopyInto(&out.RayClusterStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingClusterStatus.
func (in *ServingClusterStatus) DeepCopy() *ServingClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ServingClusterStatus)
	in.DeepCopyInto(out)
	return out
}
